version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api-gateway:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  control-plane:
    build: ./control_plane
    depends_on:
      - redis

  worker:
    build: ./workers
    depends_on:
      - redis

volumes:
  redis-data:
