name: Code Coverage
on:
  push:
    branches: [main]
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo coverage
        run: echo "codecov"
